version: 2
jobs:
  perl-latest:
    working_directory: ~/intercom-perl
    docker:
      - image: perl:latest
    steps:
      - checkout
      - run: cpanm Net::SSLeay
      - run: cpanm Devel::Cover
      - run: cpanm Devel::Cover::Report::Codecov
      - run: cpanm --installdeps .
      - store_artifacts:
          path: /root/.cpanm/build.log
      - run:
          command: perl Build.PL && ./Build build
          name: build app
      - run:
          command: cover -test -report codecov
          name: run tests
  perl-5.28:
    docker:
      - image: perl:5.28
    working_directory: ~/intercom-perl
    steps:
      - checkout
      - run: cpanm --installdeps .
      - run:
          command: perl Build.PL && ./Build build
          name: build app
      - run:
          command: ./Build test
          name: run tests
      - store_artifacts:
          path: /root/.cpanm/build.log
  perl-5.26:
    docker:
      - image: perl:5.26
    working_directory: ~/intercom-perl
    steps:
      - checkout
      - run: cpanm --installdeps .
      - run:
          command: perl Build.PL && ./Build build
          name: build app
      - run:
          command: ./Build test
          name: run tests
      - store_artifacts:
          path: /root/.cpanm/build.log
  perl-5.24:
    docker:
      - image: perl:5.24
    working_directory: ~/intercom-perl
    steps:
      - checkout
      - run: cpanm --installdeps .
      - run:
          command: perl Build.PL && ./Build build
          name: build app
      - run:
          command: ./Build test
          name: run tests
      - store_artifacts:
          path: /root/.cpanm/build.log
workflows:
  version: 2
  test:
    jobs:
      - perl-latest
      - perl-5.28
      - perl-5.26
      - perl-5.24
