version: 2
jobs:
  perl-latest: &test
    docker:
      - image: perl:latest
    working_directory: ~/intercom-perl
    steps:
      - checkout
      - run: cpanm --installdeps .
      - run: perl Build.PL && cover -test
  perl-5.28:
    <<: *test
    docker:
      - image: perl:5.28
  perl-5.26:
    <<: *test
    docker:
      - image: perl:5.26
  perl-5.24:
    <<: *test
    docker:
      - image: perl:5.24
workflows:
  version: 2
  test:
    jobs:
      - perl-latest
      - perl-5.28
      - perl-5.26
      - perl-5.24
