common_build_steps: &common_build_steps
  - checkout
  - run: cpanm Net::SSLeay
  - run: cpanm --installdeps .
  - run:
      command: perl Build.PL && ./Build build
      name: build app
  - store_artifacts:
      path: /root/.cpanm/build.log

workflow_defaults: &workflow_defaults
  working_directory: ~/intercom-perl
  steps:
    <<: *common_build_steps
    - run:
        command: ./Build test
        name: run tests

version: 2
jobs:
  perl-latest:
    <<: *workflow_defaults
    docker:
      - image: perl:latest
    steps:
      <<: *common_build_steps
      - run:
          command: cover -test -report codecov
          name: run tests
  perl-5.28:
    <<: *workflow_defaults
    docker:
      - image: perl:5.28
  perl-5.26:
    <<: *workflow_defaults
    docker:
      - image: perl:5.26
  perl-5.24:
    <<: *workflow_defaults
    docker:
      - image: perl:5.24
workflows:
  version: 2
  test:
    jobs:
      - perl-latest
      - perl-5.28
      - perl-5.26
      - perl-5.24
